#!/bin/bash

echo "🚀 Push to GitHub - andretaki/order-management"
echo "============================================="
echo ""
echo "📝 Instructions:"
echo "1. Go to https://github.com/new"
echo "2. Create a new repository named: order-management"
echo "3. Make it public or private as you prefer"
echo "4. DO NOT initialize with README, .gitignore, or license"
echo "5. After creating, run the commands below:"
echo ""
echo "📋 Commands to run after creating the repo:"
echo "============================================="
echo ""
echo "git remote add origin https://github.com/andretaki/order-management.git"
echo "git push -u origin main"
echo ""
echo "Or if you prefer SSH:"
echo "git remote add origin git@github.com:andretaki/order-management.git"
echo "git push -u origin main"
echo ""
echo "📦 Repository is ready with:"
echo "- 116 files"
echo "- Complete Next.js application"
echo "- All configurations"
echo "- Deployment scripts"
echo "- Tests"
echo ""
echo "🎉 Your code is committed and ready to push!"